### ISSUE TITLE
Guide documentation page not working

### ISSUE THREAD

**Issue by orucmahmood** [rex-lapis/Hackintosh-Dell-G7-7588-OpenCore#12]
Hi. The guide documentation link not working. Can you please update it ?

Thanks in advance.

**Comment by 13thdemarch** [comment]
Fixed.
You can check it here: https://naratouma526.github.io/g7-7588-guide/getting-started/

**Comment by orucmahmood** [comment]
> Fixed. You can check it here: https://naratouma526.github.io/g7-7588-guide/getting-started/

Oh. Thanks a lot 👍

**Comment by orucmahmood** [comment]
Hi. Not working latest link :(

**Comment by 13thdemarch** [comment]
> Hi. Not working latest link :(

https://serouin.github.io/g7-7588-guide/getting-started/
Mine is ok.
