### ISSUE TITLE
Can u share this wallpaper?

### ISSUE THREAD

**Issue by OfficialTeamFlexVN** [rex-lapis/Hackintosh-Dell-G7-7588-OpenCore#2]
![154714312_911727146321684_8606340254580982056_n](https://user-images.githubusercontent.com/69947841/115331467-2581fa00-a1c0-11eb-9275-c1ea19cd5268.jpg)

**Comment by 13thdemarch** [comment]
sry, this one can't
i got permission from its author so cant share to public
