### ISSUE TITLE
Is macOS 11 Big Sur supported?

### ISSUE THREAD

**Issue by sfc9982** [rex-lapis/Hackintosh-Dell-G7-7588-OpenCore#9]
Is MacOS 11 Big Sur supported?

When booting macOS 11, it stucks on Apple's logo without progress bar.

Using OpenCore EFI from this Repo.

After changing to clover bootloader from image, it booted successfully.

Thank you.

**Comment by 13thdemarch** [comment]
You should run CFGUnlock.efi at boot menu first to unlock the CFG-Lock. I have already disabled AppleXcpm quirk in my config.
Run the tool, press Y then restart the machine.
Let me know the result if you're done.
Cheer.

**Comment by sfc9982** [comment]
> You should run CFGUnlock.efi at boot menu first to unlock the CFG-Lock. I have already disabled AppleXcpm quirk in my config. Run the tool, press Y then restart the machine. Let me know the result if you're done. Cheer.

It's part of guide, sorry for missing that. Now trying.

**Comment by 13thdemarch** [comment]
> Is MacOS 11 Big Sur supported?
> 
> 
> 
> When booting macOS 11, it stucks on Apple's logo without progress bar.
> 
> 
> 
> Using OpenCore EFI from this Repo.
> 
> 
> 
> After changing to clover bootloader from image, it booted successfully.
> 
> 
> 
> Thank you.

Clover somehow doesn't need to unlock the CFG, I don't know why. But for better stability, I recommend you can check the KernelXCPM in Clover's config.plist.

**Comment by sfc9982** [comment]
I can't see `CFGUnlock.efi` in boot menu, but it do enabled in `config.plist`.

**Comment by 13thdemarch** [comment]
> I can't see `CFGUnlock.efi` in boot menu, but it do enabled in `config.plist`.

Press Space button at boot menu, it will show everything.

**Comment by sfc9982** [comment]
> > I can't see `CFGUnlock.efi` in boot menu, but it do enabled in `config.plist`.
> 
> Press Space button at boot menu, it will show everything.

Thanks! It works!

I have few new questions:
- Can I fork and translate it? I will quote you.
- When I power off the system, it will go black, but fan still running, I need to hold power button to shutdown.

**Comment by 13thdemarch** [comment]
> > > I can't see `CFGUnlock.efi` in boot menu, but it do enabled in `config.plist`.
> 
> > 
> 
> > Press Space button at boot menu, it will show everything.
> 
> 
> 
> Thanks! It works!
> 
> 
> 
> I have few new questions:
> 
> - Can I fork and translate it? I will quote you.
> 
> - When I power off the system, it will go black, but fan still running, I need to hold power button to shutdown.

- Yes of course 👍🏻
- Maybe there are some issues which still existed but I haven't met. Can you fully power off the machine then try again? Currently everything is still working correctly on my machine.

**Comment by sfc9982** [comment]
Basically done with Hackintosh on 7588, your guide and files are really helpful.
Wishing them help more.

**Comment by sfc9982** [comment]
Another question.
After running the Post-install script, sleep function in macOS works well.
But when I shut down both in macOS and Windows, cpu fan will still running.
What may cause that?

**Comment by 13thdemarch** [comment]
> Another question.
> 
> After running the Post-install script, sleep function in macOS works well.
> 
> But when I shut down both in macOS and Windows, cpu fan will still running.
> 
> What may cause that?

Can you check your machine 😂? I have just checked my laptop and it shutdowns completely both Mac and Windows lol.

**Comment by sfc9982** [comment]
Very weird. Even if I use Windows Boot Manager to boot Windows, it still stuck after shutting-down.

**Comment by 13thdemarch** [comment]
Try to update to the latest BIOS version. Then in the BIOS setting, restore the BIOS to BIOS Default.
You may reconfig the BIOS again to run Hackintosh, also run the CFGUnlock tool.

**Comment by sfc9982** [comment]
> Try to update to the latest BIOS version. Then in the BIOS setting, restore the BIOS to BIOS Default.
> You may reconfig the BIOS again to run Hackintosh, also run the CFGUnlock tool.

Tried everything but still meet the problem. We have the same hardware, I really don't know why it happened on me. 😂

**Comment by 13thdemarch** [comment]
> > Try to update to the latest BIOS version. Then in the BIOS setting, restore the BIOS to BIOS Default.
> > You may reconfig the BIOS again to run Hackintosh, also run the CFGUnlock tool.
> 
> Tried everything but still meet the problem. We have the same hardware, I really don't know why it happened on me. 😂

If you tried to boot to Windows via UEFI Menu Boot F12 and it still happening, I think you should check your machine. This is the first time I meet this issue 🤣

**Comment by sfc9982** [comment]
> > > Try to update to the latest BIOS version. Then in the BIOS setting, restore the BIOS to BIOS Default.
> > > You may reconfig the BIOS again to run Hackintosh, also run the CFGUnlock tool.
> > 
> > Tried everything but still meet the problem. We have the same hardware, I really don't know why it happened on me. 😂
> 
> If you tried to boot to Windows via UEFI Menu Boot F12 and it still happening, I think you should check your machine. This is the first time I meet this issue 🤣

Gonna explore Dell's deep dark magic tonight, I will let you know if I solve it.

**Comment by sfc9982** [comment]
Test with pure Windows, happened again.
Maybe my hardware problem 😭.

**Comment by 13thdemarch** [comment]
> Test with pure Windows, happened again. Maybe my hardware problem 😭.

That's sad...
Oh and about the guide, you can check the source here:
https://drive.google.com/file/d/1NVHKcGD-FBI2Ne0Tb5Q0BMygI72S9JWl/view?usp=sharing
It was built and released by mkdocs-material, automatically convert .md file to .html and publish to the website. Feel free to download and use.
Sorry I don't know how to send you the message.

**Comment by sfc9982** [comment]
> > Test with pure Windows, happened again. Maybe my hardware problem 😭.
> 
> That's sad...
> Oh and about the guide, you can check the source here:
> https://drive.google.com/file/d/1NVHKcGD-FBI2Ne0Tb5Q0BMygI72S9JWl/view?usp=sharing
> It was built and released by mkdocs-material, automatically convert .md file to .html and publish to the website. Feel free to download and use.
> Sorry I don't know how to send you the message.

OK

**Comment by sfc9982** [comment]
For you and who else search and got the same issue.

I solved it by re-plug battery and CR20xx small round battery (I forget the name)  in my computer.

Really tough but fun journey to use Hackintosh. 😄

**Comment by 13thdemarch** [comment]
> For you and who else search and got the same issue.
> 
> I solved it by re-plug battery and CR20xx small round battery (I forget the name) in my computer.
> 
> Really tough but fun journey to use Hackintosh. 😄

lol the CMOS battery? 😂

**Comment by sfc9982** [comment]
> > For you and who else search and got the same issue.
> > 
> > I solved it by re-plug battery and CR20xx small round battery (I forget the name) in my computer.
> > 
> > Really tough but fun journey to use Hackintosh. 😄
> 
> lol the CMOS battery? 😂

Yes.

By the way, are you studying Chinese?

**Comment by 13thdemarch** [comment]
> > > For you and who else search and got the same issue.
> > > I solved it by re-plug battery and CR20xx small round battery (I forget the name) in my computer.
> > > Really tough but fun journey to use Hackintosh. 😄
> > 
> > 
> > lol the CMOS battery? 😂
> 
> Yes.
> 
> By the way, are you studying Chinese?

I was before in university, but just in a semester because it was optional subject 😅

**Comment by sfc9982** [comment]
OK, wish you happy.

Case closed.
